######################################################################
# Automatically generated by qmake (3.0) Fr Jan 30 13:02:44 2015
######################################################################

TEMPLATE = app
TARGET = E12_ChannelFlow_Analyse
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += dialog.h plotter.h
SOURCES += dialog.cpp main.cpp plotter.cpp
